
spring:
  application:
    name: items-service

#Perfil local
  config:
    activate:
      on-profile:
      - local

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=America/Santiago
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082      
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
 