server:
  port: 8081

spring:
  application:
    name: registry-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lushopai/microservicios-arriendos.git
          searchPaths: config-data
          username: luxo.lyr@gmail.com
          password: Yanezlu1
          default-label: "main"


  security:
    user:
      name: root
      password: secret